---
name: Linux Tests

on:
    push:
    pull_request:
        branches: [stable]

permissions:
    contents: read

jobs:
    build:
        name: Build Test Linux
        runs-on: ubuntu-latest
        outputs:
            sha_short: ${{ steps.vars.outputs.sha_short }}

        steps:
            - name: Check out code from GitHub
              uses: actions/checkout@v7

            - name: Set up Python
              uses: actions/setup-python@v7
              with:
                  python-version: "3.14"

            - name: Install dependencies
              run: |
                  python3 -m pip install --upgrade pip
                  pip3 install -r requirements.txt

            - name: Build Executable
              run: |
                  chmod +x build-scripts/build-linux.sh
                  ./build-scripts/build-linux.sh

            - name: Verify build outputs
              run: |
                  expected=(
                      "pyguard"
                  )

                  for file in "${expected[@]}"; do
                      if [[ ! -f "$file" ]]; then
                          echo "::error::Build output missing: $file"
                          exit 1
                      else
                          echo "OK: $file"
                      fi
                  done

            - name: Compute Commit SHA
              id: vars
              run: |
                  echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

            - name: Archive artifact
              uses: actions/upload-artifact@v7
              with:
                  name: pyguard-linux_${{ steps.vars.outputs.sha_short }}
                  path: |
                      pyguard

    obfuscation-multifile-linux:
        name: Multi-file Obfuscation Linux
        needs: ["build"]
        runs-on: ubuntu-latest

        steps:
            - name: Check out code from GitHub
              uses: actions/checkout@v7

            - name: Set up Python
              uses: actions/setup-python@v7
              with:
                  python-version: "3.14"

            - name: Install dependencies
              run: |
                  python3 -m pip install --upgrade pip
                  pip3 install -r requirements.txt

            - name: Download Executable
              uses: actions/download-artifact@v8
              with:
                  name: pyguard-linux_${{ needs.build.outputs.sha_short }}
                  path: "examples"

            - name: Preparation For Test
              working-directory: examples
              run: |
                  mv pyguard multifile/
                  chmod +x multifile/pyguard
                  rm -rf multifile/obfuscated

            - name: Obfuscation Test
              working-directory: examples/multifile
              run: |
                  ./pyguard obfuscate --aes --hashdata --fernet --chacha --salsa --base64 --recursive 4 --follow-imports --no-input --files lib.py main.py

            - name: Testing Results
              working-directory: examples/multifile/obfuscated
              run: |
                  OUTPUT=$(python main.py)
                  echo "Output: $OUTPUT"

                  echo "Result: "
                  if [ "$OUTPUT" = "hello world" ]; then
                    echo "Success: main.py output contains 'hello world'"
                  else
                    echo "Failure: main.py output does not contain 'hello world'"
                    exit 1
                  fi

    obfuscation-onefile-linux:
        name: One-file Obfuscation Linux
        needs: ["build"]
        runs-on: ubuntu-latest

        steps:
            - name: Check out code from GitHub
              uses: actions/checkout@v7

            - name: Set up Python
              uses: actions/setup-python@v7
              with:
                  python-version: "3.14"

            - name: Install dependencies
              run: |
                  python3 -m pip install --upgrade pip
                  pip3 install -r requirements.txt

            - name: Download Executable
              uses: actions/download-artifact@v8
              with:
                  name: pyguard-linux_${{ needs.build.outputs.sha_short }}
                  path: "examples"

            - name: Preparation For Test
              working-directory: examples
              run: |
                  mv pyguard onefile/
                  chmod +x onefile/pyguard
                  rm -rf onefile/obfuscated

            - name: Obfuscation Test
              working-directory: examples/onefile
              run: |
                  ./pyguard obfuscate --aes --hashdata --fernet --chacha --salsa --base64 --recursive 4 --follow-imports --no-input main.py

            - name: Testing Results
              working-directory: examples/onefile/obfuscated
              run: |
                  OUTPUT=$(python main.py)
                  echo "Output: $OUTPUT"

                  echo "Result: "
                  if [ "$OUTPUT" = "hello world" ]; then
                    echo "Success: main.py output contains 'hello world'"
                  else
                    echo "Failure: main.py output does not contain 'hello world'"
                    exit 1
                  fi

    obfuscationlegacy-multifile-linux:
        name: Multi-file Legacy Obfuscation Linux
        needs: ["build"]
        runs-on: ubuntu-latest

        steps:
            - name: Check out code from GitHub
              uses: actions/checkout@v7

            - name: Set up Python
              uses: actions/setup-python@v7
              with:
                  python-version: "3.14"

            - name: Install dependencies
              run: |
                  python3 -m pip install --upgrade pip
                  pip3 install -r requirements.txt

            - name: Download Executable
              uses: actions/download-artifact@v8
              with:
                  name: pyguard-linux_${{ needs.build.outputs.sha_short }}
                  path: "examples"

            - name: Preparation For Test
              working-directory: examples
              run: |
                  mv pyguard multifile-legacy/
                  chmod +x multifile-legacy/pyguard
                  rm -rf multifile-legacy/obfuscated

            - name: Obfuscation Test
              working-directory: examples/multifile-legacy
              run: |
                  ./pyguard obfuscatelegacy --no-input --mode 4 --loops 6 --files lib.py,main.py

            - name: Testing Results
              working-directory: examples/multifile-legacy/obfuscated
              run: |
                  OUTPUT=$(python main.py)
                  echo "Output: $OUTPUT"

                  echo "Result: "
                  if [ "$OUTPUT" = "hello world" ]; then
                    echo "Success: main.py output contains 'hello world'"
                  else
                    echo "Failure: main.py output does not contain 'hello world'"
                    exit 1
                  fi

    obfuscationlegacy-onefile-linux:
        name: One-file Legacy Obfuscation Linux
        needs: ["build"]
        runs-on: ubuntu-latest

        steps:
            - name: Check out code from GitHub
              uses: actions/checkout@v7

            - name: Set up Python
              uses: actions/setup-python@v7
              with:
                  python-version: "3.14"

            - name: Install dependencies
              run: |
                  python3 -m pip install --upgrade pip
                  pip3 install -r requirements.txt

            - name: Download Executable
              uses: actions/download-artifact@v8
              with:
                  name: pyguard-linux_${{ needs.build.outputs.sha_short }}
                  path: "examples"

            - name: Preparation For Test
              working-directory: examples
              run: |
                  mv pyguard onefile-legacy/
                  chmod +x onefile-legacy/pyguard
                  rm -rf onefile-legacy/obfuscated

            - name: Obfuscation Test
              working-directory: examples/onefile-legacy
              run: |
                  ./pyguard obfuscatelegacy --no-input --mode 4 --loops 6 --files main.py

            - name: Testing Results
              working-directory: examples/onefile-legacy/obfuscated
              run: |
                  OUTPUT=$(python main.py)
                  echo "Output: $OUTPUT"

                  echo "Result: "
                  if [ "$OUTPUT" = "hello world" ]; then
                    echo "Success: main.py output contains 'hello world'"
                  else
                    echo "Failure: main.py output does not contain 'hello world'"
                    exit 1
                  fi
